/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PlayerRole = IDL.Variant({
  'allRounder' : IDL.Null,
  'bowler' : IDL.Null,
  'wicketKeeper' : IDL.Null,
  'batsman' : IDL.Null,
});
export const PlayerCategory = IDL.Variant({
  'uncappedIndian' : IDL.Null,
  'cappedIndian' : IDL.Null,
  'foreign' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AuctionId = IDL.Nat;
export const AuctionStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'live' : IDL.Null,
  'completed' : IDL.Null,
  'paused' : IDL.Null,
});
export const Player = IDL.Record({
  'name' : IDL.Text,
  'role' : PlayerRole,
  'stats' : IDL.Opt(IDL.Text),
  'category' : PlayerCategory,
  'photo' : ExternalBlob,
  'isDeletable' : IDL.Bool,
  'basePrice' : IDL.Nat,
});
export const TeamStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Team = IDL.Record({
  'status' : TeamStatus,
  'owner' : IDL.Text,
  'ownerPrincipal' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'registeredTime' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPlayer' : IDL.Func(
      [
        IDL.Text,
        PlayerRole,
        PlayerCategory,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        ExternalBlob,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'adminAuthenticate' : IDL.Func([IDL.Text], [], []),
  'approveAllTeams' : IDL.Func([], [], []),
  'approveTeam' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAuction' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [AuctionId],
      [],
    ),
  'currentAuctionState' : IDL.Func([], [IDL.Opt(AuctionStatus)], ['query']),
  'currentPlayer' : IDL.Func([], [IDL.Opt(Player)], ['query']),
  'deletePlayer' : IDL.Func([IDL.Nat], [], []),
  'getCallerTeam' : IDL.Func([IDL.Text], [Team], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlayer' : IDL.Func([IDL.Nat], [Player], ['query']),
  'getPlayers' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Player))], ['query']),
  'getTeam' : IDL.Func([IDL.Text], [Team], ['query']),
  'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'myRole' : IDL.Func([], [UserRole], ['query']),
  'registerTeam' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'rejectAllTeams' : IDL.Func([], [], []),
  'rejectTeam' : IDL.Func([IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateAuctionState' : IDL.Func([AuctionStatus], [], []),
  'updateCurrentPlayer' : IDL.Func([IDL.Nat], [], []),
  'updatePlayerState' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PlayerRole = IDL.Variant({
    'allRounder' : IDL.Null,
    'bowler' : IDL.Null,
    'wicketKeeper' : IDL.Null,
    'batsman' : IDL.Null,
  });
  const PlayerCategory = IDL.Variant({
    'uncappedIndian' : IDL.Null,
    'cappedIndian' : IDL.Null,
    'foreign' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AuctionId = IDL.Nat;
  const AuctionStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
    'paused' : IDL.Null,
  });
  const Player = IDL.Record({
    'name' : IDL.Text,
    'role' : PlayerRole,
    'stats' : IDL.Opt(IDL.Text),
    'category' : PlayerCategory,
    'photo' : ExternalBlob,
    'isDeletable' : IDL.Bool,
    'basePrice' : IDL.Nat,
  });
  const TeamStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Team = IDL.Record({
    'status' : TeamStatus,
    'owner' : IDL.Text,
    'ownerPrincipal' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'registeredTime' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPlayer' : IDL.Func(
        [
          IDL.Text,
          PlayerRole,
          PlayerCategory,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          ExternalBlob,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'adminAuthenticate' : IDL.Func([IDL.Text], [], []),
    'approveAllTeams' : IDL.Func([], [], []),
    'approveTeam' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAuction' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [AuctionId],
        [],
      ),
    'currentAuctionState' : IDL.Func([], [IDL.Opt(AuctionStatus)], ['query']),
    'currentPlayer' : IDL.Func([], [IDL.Opt(Player)], ['query']),
    'deletePlayer' : IDL.Func([IDL.Nat], [], []),
    'getCallerTeam' : IDL.Func([IDL.Text], [Team], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlayer' : IDL.Func([IDL.Nat], [Player], ['query']),
    'getPlayers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Player))],
        ['query'],
      ),
    'getTeam' : IDL.Func([IDL.Text], [Team], ['query']),
    'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'myRole' : IDL.Func([], [UserRole], ['query']),
    'registerTeam' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'rejectAllTeams' : IDL.Func([], [], []),
    'rejectTeam' : IDL.Func([IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateAuctionState' : IDL.Func([AuctionStatus], [], []),
    'updateCurrentPlayer' : IDL.Func([IDL.Nat], [], []),
    'updatePlayerState' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };